import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./theme-config.css";
import Navbar from "./Navbar";
// import radix ui
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Define the RootLayout component
const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <>
      {/* Use Head component to set metadata and font style */}
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
        <style>{`body { font-family: ${inter.variable}; }`}</style>
      </Head>

      {/* Rest of the component */}
      <Theme>
        <Navbar />
        <main>{children}</main>
      </Theme>
    </>
  );
};

export default RootLayout;
